---
- name: install and start docker
  hosts: all
  tasks:
    - name: install docker prerequisites
      become: yes
      apt:
        name: 
          - ca-certificates 
          - curl 
          - gnupg 
          - lsb-release
        update_cache: yes
    - name: add keyrings path
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
    - name: add docker GPG key
      become: yes
      shell: "{{ item }}"
      with_items:
        - rm /etc/apt/keyrings/docker.gpg
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - name: set up docker repository
      become: yes
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: install docker engine
      become: yes
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes
    - name: create docker group
      become: yes
      group:
        name: docker
        state: present
    - name: add user to the docker group
      become: yes
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
    - name: activate group changes
      shell: newgrp docker
